### ISSUE TITLE
[Performance] Synchronous cURL requests on every page load

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-local_leeloolxp_web_login_tracking#1]
This is similar performace issue to the one raised in the tool plugin. Here in `local_leeloolxp_web_login_tracking_before_footer()` there are synchronous cURL requests on every page load. Are they really needed? Could not they be limited to once per session or so?

**Comment by anayleeloolxp** [comment]
@mudrd8mz Have removed the repeated curl calls and have managed those by session per user. But still there are some curl calls and those are needed for the plugin to work.
