### ISSUE TITLE
Am I expected to receive passwords etc from the API

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-local_leeloolxp_web_login_tracking#2]
When I contact https://leeloolxp.com/api_moodle.php/?action=page_info and provide my license number, I get various data - some of which sounds pretty sensitive. Such as `db_user` and `db_password` or `ftp_host`, `ftp_username` and `ftp_password`.

Are they actually expected to be shared like this? Can someone simply try to guess my license number (or have a script that tries them all in a sequence) to get such data? I seem to have FTP access to some site through this FTP - what server is it?

![image](https://user-images.githubusercontent.com/85831/111485710-26de8380-8737-11eb-802f-de4f0bee7166.png)

**Comment by anayleeloolxp** [comment]
Hello @mudrd8mz 
That was not expected, had removed those parameters from the API.
