### ISSUE TITLE
Notices when installing the plugin 

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-local_leeloolxp_web_login_tracking#3]
As I am installing and setting up the plugin for the first time, I get

    Notice: Undefined property: stdClass::$web_new_user_student in .../local/leeloolxp_web_login_tracking/lib.php on line 619

    Notice: Undefined property: stdClass::$default_student_position in .../local/leeloolxp_web_login_tracking/lib.php on line 620

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Functionality

**Comment by anayleeloolxp** [comment]
Hello @mudrd8mz Thanks for informing about the issue. We have fixed the issue and have created a new release of plugin.
